[tool.poetry]
name = "heytorvas"
version = "0.0.3"
description = "Heytor Victor's Portfolio"
authors = ["Heytor Victor <heytor@heytor.dev>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
rich = "13.7.1"
typer = "0.12.3"
pytest = "8.2.2"

[tool.poetry.scripts]
heytorvas = "heytorvas.main:main"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
